name: luca
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  url_strategy: ^0.2.0
  quiver: ^3.1.0
  path_to_regexp: ^0.4.0
  url_launcher: ^6.1.5
  adaptive_navigation: ^0.0.7
  http: ^0.13.5
  getwidget: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  fonts:
    - family:  Scaffold_icon
      fonts:
        - asset: fonts/Scaffold_icon.ttf

    - family:  Segoe Ui
      fonts:
        - asset: fonts/Segoe UI.ttf
        - asset: fonts/Segoe UI Bold.ttf
          weight: 700

    - family:  Parisine
      fonts:
        - asset: fonts/Parisine-Regular.otf
        - asset: fonts/Parisine-Bold.otf
          weight: 700

  assets:
    - assets/idfm/lines_small_dark/METRO_1.png
    - assets/idfm/lines_small_dark/METRO_2.png
    - assets/idfm/lines_small_dark/METRO_3.png
    - assets/idfm/lines_small_dark/METRO_3B.png
    - assets/idfm/lines_small_dark/METRO_4.png
    - assets/idfm/lines_small_dark/METRO_5.png
    - assets/idfm/lines_small_dark/METRO_6.png
    - assets/idfm/lines_small_dark/METRO_7.png
    - assets/idfm/lines_small_dark/METRO_7B.png
    - assets/idfm/lines_small_dark/METRO_8.png
    - assets/idfm/lines_small_dark/METRO_9.png
    - assets/idfm/lines_small_dark/METRO_10.png
    - assets/idfm/lines_small_dark/METRO_11.png
    - assets/idfm/lines_small_dark/METRO_12.png
    - assets/idfm/lines_small_dark/METRO_13.png
    - assets/idfm/lines_small_dark/METRO_14.png
    - assets/Val/ORLYVAL.png
    - assets/idfm/lines_small_dark/RER_A.png
    - assets/idfm/lines_small_dark/RER_B.png
    - assets/idfm/lines_small_dark/RER_C.png
    - assets/idfm/lines_small_dark/RER_D.png
    - assets/idfm/lines_small_dark/RER_E.png
    - assets/idfm/lines_small_dark/TRAIN_H.png
    - assets/idfm/lines_small_dark/TRAIN_J.png
    - assets/idfm/lines_small_dark/TRAIN_K.png
    - assets/idfm/lines_small_dark/TRAIN_L.png
    - assets/idfm/lines_small_dark/TRAIN_N.png
    - assets/idfm/lines_small_dark/TRAIN_P.png
    - assets/idfm/lines_small_dark/TRAIN_R.png
    - assets/idfm/lines_small_dark/TRAIN_U.png
    - assets/idfm/lines_small_dark/TRAM_1.png
    - assets/idfm/lines_small_dark/TRAM_2.png
    - assets/idfm/lines_small_dark/TRAM_3A.png
    - assets/idfm/lines_small_dark/TRAM_3B.png
    - assets/idfm/lines_small_dark/TRAM_4.png
    - assets/idfm/lines_small_dark/TRAM_5.png
    - assets/idfm/lines_small_dark/TRAM_6.png
    - assets/idfm/lines_small_dark/TRAM_7.png
    - assets/idfm/lines_small_dark/TRAM_8.png
    - assets/idfm/lines_small_dark/TRAM_9.png
    - assets/idfm/lines_small_dark/TRAM_11.png
    - assets/idfm/lines_small_dark/TRAM_13.png

    - assets/Noctilien/NOCT_133.png
    - assets/Noctilien/NOCT_42.png
    - assets/Noctilien/NOCT_52.png
    - assets/Noctilien/NOCT_21.png
    - assets/Noctilien/NOCT_32.png
    - assets/Noctilien/NOCT_43.png
    - assets/Noctilien/NOCT_71.png
    - assets/Noctilien/NOCT_14.png
    - assets/Noctilien/NOCT_66.png
    - assets/Noctilien/NOCT_132.png
    - assets/Noctilien/NOCT_141.png
    - assets/Noctilien/NOCT_145.png
    - assets/Noctilien/NOCT_01.png
    - assets/Noctilien/NOCT_02.png
    - assets/Noctilien/NOCT_131.png
    - assets/Noctilien/NOCT_23.png
    - assets/Noctilien/NOCT_34.png
    - assets/Noctilien/NOCT_31.png
    - assets/Noctilien/NOCT_45.png
    - assets/Noctilien/NOCT_53.png
    - assets/Noctilien/NOCT_16.png
    - assets/Noctilien/NOCT_122.png
    - assets/Noctilien/NOCT_140.png
    - assets/Noctilien/NOCT_24.png
    - assets/Noctilien/NOCT_44.png
    - assets/Noctilien/NOCT_62.png
    - assets/Noctilien/NOCT_22.png
    - assets/Noctilien/NOCT_35.png
    - assets/Noctilien/NOCT_15.png
    - assets/Noctilien/NOCT_153.png
    - assets/Noctilien/NOCT_150.png
    - assets/Noctilien/NOCT_152.png
    - assets/Noctilien/NOCT_135.png
    - assets/Noctilien/NOCT_143.png
    - assets/Noctilien/NOCT_33.png
    - assets/Noctilien/NOCT_61.png
    - assets/Noctilien/NOCT_11.png
    - assets/Noctilien/NOCT_151.png
    - assets/Noctilien/NOCT_134.png
    - assets/Noctilien/NOCT_144.png
    - assets/Noctilien/NOCT_130.png
    - assets/Noctilien/NOCT_51.png
    - assets/Noctilien/NOCT_63.png
    - assets/Noctilien/NOCT_41.png
    - assets/Noctilien/NOCT_13.png
    - assets/Noctilien/NOCT_12.png
    - assets/Noctilien/NOCT_142.png
    - assets/Noctilien/NOCT_154.png

    - assets/idfm/BUS_dark.png
    - assets/idfm/BUS_white.png
    - assets/idfm/METRO_dark.png
    - assets/idfm/METRO_white.png
    - assets/idfm/RER_dark.png
    - assets/idfm/RER_white.png
    - assets/idfm/TRAIN_dark.png
    - assets/idfm/TRAIN_white.png
    - assets/idfm/TRAM_dark.png
    - assets/idfm/TRAM_white.png
    - assets/idfm/NOCTILIEN_dark.png
    - assets/idfm/NOCTILIEN_white.png

    - assets/work_white_small.png
    - assets/alert.png
    - assets/alert_small.png
    - assets/alert_white.png
    - assets/alert_white_small.png
    - assets/error.png
    - assets/error_small.png
    - assets/error_white.png
    - assets/error_white_small.png
    - assets/futur_work.png
    - assets/futur_work_small.png
    - assets/information.png
    - assets/information_small.png
    - assets/information_white.png
    - assets/information_white_small.png
    - assets/interogation.png
    - assets/interogation_grey.png
    - assets/interogation_grey_small.png
    - assets/interogation_small.png
    - assets/interogation_white.png
    - assets/interogation_white_small.png
    - assets/valid.png
    - assets/valid_small.png
    - assets/valid_white.png
    - assets/valid_white_small.png
    - assets/warning.png
    - assets/warning_small.png
    - assets/warning_white.png
    - assets/work.png
    - assets/work_small.png
    - assets/work_white.png
    - assets/null.png



  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
