name: navika
description: Navika.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  url_strategy: ^0.2.0
  quiver: ^3.1.0
  path_to_regexp: ^0.4.0
  url_launcher: ^6.1.5
  adaptive_navigation: ^0.0.7
  http: ^0.13.5
  location: ^4.4.0
  sliding_up_panel: ^2.0.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^1.1.6
  flutter_inappwebview: ^5.7.2
  collection: ^1.16.0
  flutter_rounded_date_picker: ^3.0.2
  firebase_messaging: ^14.2.1

  flutter_localizations:
    sdk: flutter

  here_sdk:
    path: plugins/here_sdk

  # flutter_compass: ^0.7.0
  flutter_compass:
    git: https://github.com/hemanthrajv/flutter_compass.git
  firebase_core: ^2.4.1
  
dev_dependencies:
  hive_generator: ^1.1.3
  build_runner: ^2.3.0
  
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  fonts:
    - family: Scaffold_icon
      fonts:
        - asset: fonts/Scaffold_icon.ttf

    - family: Segoe Ui
      fonts:
        - asset: fonts/Segoe UI.ttf
        - asset: fonts/Segoe UI Bold.ttf
          weight: 700

    - family:  Diode
      fonts:
        - asset: fonts/TransilienSmall.ttf

  assets:
    - assets/icons/TRAM_white.png
    - assets/icons/TRAM_white.png
    - assets/icons/BUS_blue.png
    - assets/icons/BUS_dark.png
    - assets/icons/BUS_white.png
    - assets/icons/CABLE_blue.png
    - assets/icons/CABLE_dark.png
    - assets/icons/CABLE_white.png
    - assets/icons/METRO_blue.png
    - assets/icons/METRO_dark.png
    - assets/icons/METRO_white.png
    - assets/icons/NAVETTE_FLUVIALE_blue.png
    - assets/icons/NAVETTE_FLUVIALE_dark.png
    - assets/icons/NAVETTE_FLUVIALE_white.png
    - assets/icons/NOCTILIEN_blue.png
    - assets/icons/NOCTILIEN_dark.png
    - assets/icons/NOCTILIEN_white.png
    - assets/icons/RER_blue.png
    - assets/icons/RER_dark.png
    - assets/icons/RER_white.png
    - assets/icons/TRAIN_blue.png
    - assets/icons/TRAIN_dark.png
    - assets/icons/TRAIN_white.png
    - assets/icons/TRAM_blue.png
    - assets/icons/TRAM_dark.png

    - assets/icons/lines/METRO_1.png
    - assets/icons/lines/METRO_2.png
    - assets/icons/lines/METRO_3.png
    - assets/icons/lines/METRO_3b.png
    - assets/icons/lines/METRO_4.png
    - assets/icons/lines/METRO_5.png
    - assets/icons/lines/METRO_6.png
    - assets/icons/lines/METRO_7.png
    - assets/icons/lines/METRO_7b.png
    - assets/icons/lines/METRO_8.png
    - assets/icons/lines/METRO_9.png
    - assets/icons/lines/METRO_10.png
    - assets/icons/lines/METRO_11.png
    - assets/icons/lines/METRO_12.png
    - assets/icons/lines/METRO_13.png
    - assets/icons/lines/METRO_14.png
    - assets/icons/lines/METRO_15.png
    - assets/icons/lines/METRO_16.png
    - assets/icons/lines/METRO_17.png
    - assets/icons/lines/METRO_18.png
    - assets/icons/lines/RER_A.png
    - assets/icons/lines/RER_B.png
    - assets/icons/lines/RER_C.png
    - assets/icons/lines/RER_D.png
    - assets/icons/lines/RER_E.png
    - assets/icons/lines/TRAIN_H.png
    - assets/icons/lines/TRAIN_J.png
    - assets/icons/lines/TRAIN_K.png
    - assets/icons/lines/TRAIN_L.png
    - assets/icons/lines/TRAIN_N.png
    - assets/icons/lines/TRAIN_P.png
    - assets/icons/lines/TRAIN_R.png
    - assets/icons/lines/TRAIN_U.png
    - assets/icons/lines/TRAM_T1.png
    - assets/icons/lines/TRAM_T2.png
    - assets/icons/lines/TRAM_T3a.png
    - assets/icons/lines/TRAM_T3b.png
    - assets/icons/lines/TRAM_T4.png
    - assets/icons/lines/TRAM_T5.png
    - assets/icons/lines/TRAM_T6.png
    - assets/icons/lines/TRAM_T7.png
    - assets/icons/lines/TRAM_T8.png
    - assets/icons/lines/TRAM_T9.png
    - assets/icons/lines/TRAM_T10.png
    - assets/icons/lines/TRAM_T11.png
    - assets/icons/lines/TRAM_T12.png
    - assets/icons/lines/TRAM_T13.png

    - assets/icons/lines_small/METRO_1.png
    - assets/icons/lines_small/METRO_2.png
    - assets/icons/lines_small/METRO_3.png
    - assets/icons/lines_small/METRO_3b.png
    - assets/icons/lines_small/METRO_4.png
    - assets/icons/lines_small/METRO_5.png
    - assets/icons/lines_small/METRO_6.png
    - assets/icons/lines_small/METRO_7.png
    - assets/icons/lines_small/METRO_7b.png
    - assets/icons/lines_small/METRO_8.png
    - assets/icons/lines_small/METRO_9.png
    - assets/icons/lines_small/METRO_10.png
    - assets/icons/lines_small/METRO_11.png
    - assets/icons/lines_small/METRO_12.png
    - assets/icons/lines_small/METRO_13.png
    - assets/icons/lines_small/METRO_14.png
    - assets/icons/lines_small/METRO_15.png
    - assets/icons/lines_small/METRO_16.png
    - assets/icons/lines_small/METRO_17.png
    - assets/icons/lines_small/METRO_18.png
    - assets/icons/lines_small/RER_A.png
    - assets/icons/lines_small/RER_B.png
    - assets/icons/lines_small/RER_C.png
    - assets/icons/lines_small/RER_D.png
    - assets/icons/lines_small/RER_E.png
    - assets/icons/lines_small/TRAIN_H.png
    - assets/icons/lines_small/TRAIN_J.png
    - assets/icons/lines_small/TRAIN_K.png
    - assets/icons/lines_small/TRAIN_L.png
    - assets/icons/lines_small/TRAIN_N.png
    - assets/icons/lines_small/TRAIN_P.png
    - assets/icons/lines_small/TRAIN_R.png
    - assets/icons/lines_small/TRAIN_U.png
    - assets/icons/lines_small/TRAM_T1.png
    - assets/icons/lines_small/TRAM_T2.png
    - assets/icons/lines_small/TRAM_T3a.png
    - assets/icons/lines_small/TRAM_T3b.png
    - assets/icons/lines_small/TRAM_T4.png
    - assets/icons/lines_small/TRAM_T5.png
    - assets/icons/lines_small/TRAM_T6.png
    - assets/icons/lines_small/TRAM_T7.png
    - assets/icons/lines_small/TRAM_T8.png
    - assets/icons/lines_small/TRAM_T9.png
    - assets/icons/lines_small/TRAM_T10.png
    - assets/icons/lines_small/TRAM_T11.png
    - assets/icons/lines_small/TRAM_T12.png
    - assets/icons/lines_small/TRAM_T13.png

    - assets/noctilien/NOCT_01.png
    - assets/noctilien/NOCT_02.png
    - assets/noctilien/NOCT_11.png
    - assets/noctilien/NOCT_12.png
    - assets/noctilien/NOCT_13.png
    - assets/noctilien/NOCT_14.png
    - assets/noctilien/NOCT_15.png
    - assets/noctilien/NOCT_16.png
    - assets/noctilien/NOCT_21.png
    - assets/noctilien/NOCT_22.png
    - assets/noctilien/NOCT_23.png
    - assets/noctilien/NOCT_24.png
    - assets/noctilien/NOCT_31.png
    - assets/noctilien/NOCT_32.png
    - assets/noctilien/NOCT_33.png
    - assets/noctilien/NOCT_34.png
    - assets/noctilien/NOCT_35.png
    - assets/noctilien/NOCT_41.png
    - assets/noctilien/NOCT_42.png
    - assets/noctilien/NOCT_43.png
    - assets/noctilien/NOCT_44.png
    - assets/noctilien/NOCT_45.png
    - assets/noctilien/NOCT_51.png
    - assets/noctilien/NOCT_52.png
    - assets/noctilien/NOCT_53.png
    - assets/noctilien/NOCT_61.png
    - assets/noctilien/NOCT_62.png
    - assets/noctilien/NOCT_63.png
    - assets/noctilien/NOCT_66.png
    - assets/noctilien/NOCT_71.png
    - assets/noctilien/NOCT_122.png
    - assets/noctilien/NOCT_130.png
    - assets/noctilien/NOCT_131.png
    - assets/noctilien/NOCT_132.png
    - assets/noctilien/NOCT_133.png
    - assets/noctilien/NOCT_134.png
    - assets/noctilien/NOCT_135.png
    - assets/noctilien/NOCT_140.png
    - assets/noctilien/NOCT_141.png
    - assets/noctilien/NOCT_142.png
    - assets/noctilien/NOCT_143.png
    - assets/noctilien/NOCT_144.png
    - assets/noctilien/NOCT_145.png
    - assets/noctilien/NOCT_150.png
    - assets/noctilien/NOCT_151.png
    - assets/noctilien/NOCT_152.png
    - assets/noctilien/NOCT_153.png
    - assets/noctilien/NOCT_154.png

    - assets/sncf/logo_white.png
    - assets/sncf/logo_color.png
    - assets/sncf/logo_dark.png
    - assets/sncf/TER_dark.png
    - assets/sncf/TER_white.png
    - assets/sncf/TER_color.png

    - assets/val/lines/CDGVAL.png
    - assets/val/lines/ORLYVAL.png
    - assets/val/lines_small/CDGVAL.png
    - assets/val/lines_small/ORLYVAL.png

    - assets/marker/marker_bike_light.png
    - assets/marker/marker_bike_dark.png
    - assets/marker/marker_bus_dark.png
    - assets/marker/marker_bus_light.png
    - assets/marker/marker_cable_dark.png
    - assets/marker/marker_cable_light.png
    - assets/marker/marker_metro_dark.png
    - assets/marker/marker_metro_light.png
    - assets/marker/marker_navette_fluviale_dark.png
    - assets/marker/marker_navette_fluviale_light.png
    - assets/marker/marker_noctilien_dark.png
    - assets/marker/marker_noctilien_light.png
    - assets/marker/marker_rer_dark.png
    - assets/marker/marker_rer_light.png
    - assets/marker/marker_train_dark.png
    - assets/marker/marker_train_light.png
    - assets/marker/marker_tram_dark.png
    - assets/marker/marker_tram_light.png
    - assets/marker/mini_bike_light.png
    - assets/marker/mini_dark.png
    - assets/marker/mini_light.png
    - assets/marker/mini_bike_dark.png
    
    - assets/modal/acces_ufr.png
    - assets/modal/acces_ufr_small.png
    - assets/modal/acces_ufr_train.png
    - assets/modal/acces_ufr_train_small.png
    - assets/modal/alert.png
    - assets/modal/alert_small.png
    - assets/modal/alert_white.png
    - assets/modal/alert_white_small.png
    - assets/modal/emergency_call.png
    - assets/modal/emergency_call_small.png
    - assets/modal/emergency_signal.png
    - assets/modal/emergency_signal_small.png
    - assets/modal/error.png
    - assets/modal/error_small.png
    - assets/modal/error_white.png
    - assets/modal/error_white_small.png
    - assets/modal/futur_work.png
    - assets/modal/futur_work_small.png
    - assets/modal/information.png
    - assets/modal/information_small.png
    - assets/modal/information_white.png
    - assets/modal/information_white_small.png
    - assets/modal/interogation.png
    - assets/modal/interogation_grey.png
    - assets/modal/interogation_grey_small.png
    - assets/modal/interogation_small.png
    - assets/modal/interogation_white.png
    - assets/modal/interogation_white_small.png
    - assets/modal/valid.png
    - assets/modal/valid_small.png
    - assets/modal/valid_white.png
    - assets/modal/valid_white_small.png
    - assets/modal/warning.png
    - assets/modal/warning_small.png
    - assets/modal/work.png
    - assets/modal/work_small.png
    - assets/modal/work_white.png
    - assets/modal/work_white_small.png

    - assets/walking.svg
    - assets/bike.png
    - assets/bussines.svg
    - assets/cancel.svg
    - assets/city.svg
    - assets/e-bike.png
    - assets/finish-flag.svg
    - assets/home.svg
    - assets/locate.svg
    - assets/location-indicator.svg
    - assets/maintenance.png
    - assets/marker.svg
    - assets/null.png
    - assets/plus.svg
    - assets/search.svg
    - assets/sign.svg
    - assets/sign_top.svg
    - assets/star.svg
    - assets/star_regular.svg
    - assets/train.svg
    - assets/university.svg

    - assets/here/HERE_logo_full.svg
    - assets/here/HERE_logo_full_inverted.svg

    - assets/maintenance.png
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
