name: navika
description: Navika.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  url_strategy: ^0.2.0
  quiver: ^3.1.0
  path_to_regexp: ^0.4.0
  url_launcher: ^6.1.5
  adaptive_navigation: ^0.0.7
  http: ^0.13.5
  location: ^4.4.0
  sliding_up_panel: ^2.0.0+1
  #flutter_compass: ^0.7.0
  flutter_compass:
    git: https://github.com/hemanthrajv/flutter_compass.git
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  here_sdk:
    path: plugins/here_sdk

dev_dependencies:
  hive_generator: ^1.1.3
  build_runner: ^2.3.0
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  fonts:
    - family:  Scaffold_icon
      fonts:
        - asset: fonts/Scaffold_icon.ttf

    - family:  Segoe Ui
      fonts:
        - asset: fonts/Segoe UI.ttf
        - asset: fonts/Segoe UI Bold.ttf
          weight: 700

    - family:  Parisine
      fonts:
        - asset: fonts/Parisine-Regular.otf
        - asset: fonts/Parisine-Bold.otf
          weight: 700

    - family:  Diode
      fonts:
        - asset: fonts/TransilienSmall.ttf

  assets:
    - assets/idfm/lines_dark/CABLE_C1.png
    - assets/idfm/lines_dark/METRO_1.png
    - assets/idfm/lines_dark/METRO_2.png
    - assets/idfm/lines_dark/METRO_3.png
    - assets/idfm/lines_dark/METRO_3bis.png
    - assets/idfm/lines_dark/METRO_4.png
    - assets/idfm/lines_dark/METRO_5.png
    - assets/idfm/lines_dark/METRO_6.png
    - assets/idfm/lines_dark/METRO_7.png
    - assets/idfm/lines_dark/METRO_7bis.png
    - assets/idfm/lines_dark/METRO_8.png
    - assets/idfm/lines_dark/METRO_9.png
    - assets/idfm/lines_dark/METRO_10.png
    - assets/idfm/lines_dark/METRO_11.png
    - assets/idfm/lines_dark/METRO_12.png
    - assets/idfm/lines_dark/METRO_13.png
    - assets/idfm/lines_dark/METRO_14.png
    - assets/idfm/lines_dark/METRO_15.png
    - assets/idfm/lines_dark/METRO_16.png
    - assets/idfm/lines_dark/METRO_17.png
    - assets/idfm/lines_dark/METRO_18.png
    - assets/idfm/lines_dark/RER_A.png
    - assets/idfm/lines_dark/RER_B.png
    - assets/idfm/lines_dark/RER_C.png
    - assets/idfm/lines_dark/RER_D.png
    - assets/idfm/lines_dark/RER_E.png
    - assets/idfm/lines_dark/TRAIN_H.png
    - assets/idfm/lines_dark/TRAIN_J.png
    - assets/idfm/lines_dark/TRAIN_K.png
    - assets/idfm/lines_dark/TRAIN_L.png
    - assets/idfm/lines_dark/TRAIN_N.png
    - assets/idfm/lines_dark/TRAIN_P.png
    - assets/idfm/lines_dark/TRAIN_R.png
    - assets/idfm/lines_dark/TRAIN_U.png
    - assets/idfm/lines_dark/TRAM_T1.png
    - assets/idfm/lines_dark/TRAM_T2.png
    - assets/idfm/lines_dark/TRAM_T3a.png
    - assets/idfm/lines_dark/TRAM_T3b.png
    - assets/idfm/lines_dark/TRAM_T4.png
    - assets/idfm/lines_dark/TRAM_T5.png
    - assets/idfm/lines_dark/TRAM_T6.png
    - assets/idfm/lines_dark/TRAM_T7.png
    - assets/idfm/lines_dark/TRAM_T8.png
    - assets/idfm/lines_dark/TRAM_T9.png
    - assets/idfm/lines_dark/TRAM_T10.png
    - assets/idfm/lines_dark/TRAM_T11.png
    - assets/idfm/lines_dark/TRAM_T12.png
    - assets/idfm/lines_dark/TRAM_T13.png
    - assets/idfm/lines_white/CABLE_C1.png

    - assets/idfm/lines_white/METRO_1.png
    - assets/idfm/lines_white/METRO_2.png
    - assets/idfm/lines_white/METRO_3.png
    - assets/idfm/lines_white/METRO_3bis.png
    - assets/idfm/lines_white/METRO_4.png
    - assets/idfm/lines_white/METRO_5.png
    - assets/idfm/lines_white/METRO_6.png
    - assets/idfm/lines_white/METRO_7.png
    - assets/idfm/lines_white/METRO_7bis.png
    - assets/idfm/lines_white/METRO_8.png
    - assets/idfm/lines_white/METRO_9.png
    - assets/idfm/lines_white/METRO_10.png
    - assets/idfm/lines_white/METRO_11.png
    - assets/idfm/lines_white/METRO_12.png
    - assets/idfm/lines_white/METRO_13.png
    - assets/idfm/lines_white/METRO_14.png
    - assets/idfm/lines_white/METRO_15.png
    - assets/idfm/lines_white/METRO_16.png
    - assets/idfm/lines_white/METRO_17.png
    - assets/idfm/lines_white/METRO_18.png
    - assets/idfm/lines_white/RER_A.png
    - assets/idfm/lines_white/RER_B.png
    - assets/idfm/lines_white/RER_C.png
    - assets/idfm/lines_white/RER_D.png
    - assets/idfm/lines_white/RER_E.png
    - assets/idfm/lines_white/TRAIN_H.png
    - assets/idfm/lines_white/TRAIN_J.png
    - assets/idfm/lines_white/TRAIN_K.png
    - assets/idfm/lines_white/TRAIN_L.png
    - assets/idfm/lines_white/TRAIN_N.png
    - assets/idfm/lines_white/TRAIN_P.png
    - assets/idfm/lines_white/TRAIN_R.png
    - assets/idfm/lines_white/TRAIN_U.png
    - assets/idfm/lines_white/TRAM_T1.png
    - assets/idfm/lines_white/TRAM_T2.png
    - assets/idfm/lines_white/TRAM_T3a.png
    - assets/idfm/lines_white/TRAM_T3b.png
    - assets/idfm/lines_white/TRAM_T4.png
    - assets/idfm/lines_white/TRAM_T5.png
    - assets/idfm/lines_white/TRAM_T6.png
    - assets/idfm/lines_white/TRAM_T7.png
    - assets/idfm/lines_white/TRAM_T8.png
    - assets/idfm/lines_white/TRAM_T9.png
    - assets/idfm/lines_white/TRAM_T10.png
    - assets/idfm/lines_white/TRAM_T11.png
    - assets/idfm/lines_white/TRAM_T12.png
    - assets/idfm/lines_white/TRAM_T13.png

    - assets/idfm/lines_dark_small/CABLE_C1.png
    - assets/idfm/lines_dark_small/METRO_1.png
    - assets/idfm/lines_dark_small/METRO_2.png
    - assets/idfm/lines_dark_small/METRO_3.png
    - assets/idfm/lines_dark_small/METRO_3bis.png
    - assets/idfm/lines_dark_small/METRO_4.png
    - assets/idfm/lines_dark_small/METRO_5.png
    - assets/idfm/lines_dark_small/METRO_6.png
    - assets/idfm/lines_dark_small/METRO_7.png
    - assets/idfm/lines_dark_small/METRO_7bis.png
    - assets/idfm/lines_dark_small/METRO_8.png
    - assets/idfm/lines_dark_small/METRO_9.png
    - assets/idfm/lines_dark_small/METRO_10.png
    - assets/idfm/lines_dark_small/METRO_11.png
    - assets/idfm/lines_dark_small/METRO_12.png
    - assets/idfm/lines_dark_small/METRO_13.png
    - assets/idfm/lines_dark_small/METRO_14.png
    - assets/idfm/lines_dark_small/METRO_15.png
    - assets/idfm/lines_dark_small/METRO_16.png
    - assets/idfm/lines_dark_small/METRO_17.png
    - assets/idfm/lines_dark_small/METRO_18.png
    - assets/idfm/lines_dark_small/RER_A.png
    - assets/idfm/lines_dark_small/RER_B.png
    - assets/idfm/lines_dark_small/RER_C.png
    - assets/idfm/lines_dark_small/RER_D.png
    - assets/idfm/lines_dark_small/RER_E.png
    - assets/idfm/lines_dark_small/TRAIN_H.png
    - assets/idfm/lines_dark_small/TRAIN_J.png
    - assets/idfm/lines_dark_small/TRAIN_K.png
    - assets/idfm/lines_dark_small/TRAIN_L.png
    - assets/idfm/lines_dark_small/TRAIN_N.png
    - assets/idfm/lines_dark_small/TRAIN_P.png
    - assets/idfm/lines_dark_small/TRAIN_R.png
    - assets/idfm/lines_dark_small/TRAIN_U.png
    - assets/idfm/lines_dark_small/TRAM_T1.png
    - assets/idfm/lines_dark_small/TRAM_T2.png
    - assets/idfm/lines_dark_small/TRAM_T3a.png
    - assets/idfm/lines_dark_small/TRAM_T3b.png
    - assets/idfm/lines_dark_small/TRAM_T4.png
    - assets/idfm/lines_dark_small/TRAM_T5.png
    - assets/idfm/lines_dark_small/TRAM_T6.png
    - assets/idfm/lines_dark_small/TRAM_T7.png
    - assets/idfm/lines_dark_small/TRAM_T8.png
    - assets/idfm/lines_dark_small/TRAM_T9.png
    - assets/idfm/lines_dark_small/TRAM_T10.png
    - assets/idfm/lines_dark_small/TRAM_T11.png
    - assets/idfm/lines_dark_small/TRAM_T12.png
    - assets/idfm/lines_dark_small/TRAM_T13.png
    - assets/idfm/lines_white_small/CABLE_C1.png

    - assets/idfm/lines_white_small/METRO_1.png
    - assets/idfm/lines_white_small/METRO_2.png
    - assets/idfm/lines_white_small/METRO_3.png
    - assets/idfm/lines_white_small/METRO_3bis.png
    - assets/idfm/lines_white_small/METRO_4.png
    - assets/idfm/lines_white_small/METRO_5.png
    - assets/idfm/lines_white_small/METRO_6.png
    - assets/idfm/lines_white_small/METRO_7.png
    - assets/idfm/lines_white_small/METRO_7bis.png
    - assets/idfm/lines_white_small/METRO_8.png
    - assets/idfm/lines_white_small/METRO_9.png
    - assets/idfm/lines_white_small/METRO_10.png
    - assets/idfm/lines_white_small/METRO_11.png
    - assets/idfm/lines_white_small/METRO_12.png
    - assets/idfm/lines_white_small/METRO_13.png
    - assets/idfm/lines_white_small/METRO_14.png
    - assets/idfm/lines_white_small/METRO_15.png
    - assets/idfm/lines_white_small/METRO_16.png
    - assets/idfm/lines_white_small/METRO_17.png
    - assets/idfm/lines_white_small/METRO_18.png
    - assets/idfm/lines_white_small/RER_A.png
    - assets/idfm/lines_white_small/RER_B.png
    - assets/idfm/lines_white_small/RER_C.png
    - assets/idfm/lines_white_small/RER_D.png
    - assets/idfm/lines_white_small/RER_E.png
    - assets/idfm/lines_white_small/TRAIN_H.png
    - assets/idfm/lines_white_small/TRAIN_J.png
    - assets/idfm/lines_white_small/TRAIN_K.png
    - assets/idfm/lines_white_small/TRAIN_L.png
    - assets/idfm/lines_white_small/TRAIN_N.png
    - assets/idfm/lines_white_small/TRAIN_P.png
    - assets/idfm/lines_white_small/TRAIN_R.png
    - assets/idfm/lines_white_small/TRAIN_U.png
    - assets/idfm/lines_white_small/TRAM_T1.png
    - assets/idfm/lines_white_small/TRAM_T2.png
    - assets/idfm/lines_white_small/TRAM_T3a.png
    - assets/idfm/lines_white_small/TRAM_T3b.png
    - assets/idfm/lines_white_small/TRAM_T4.png
    - assets/idfm/lines_white_small/TRAM_T5.png
    - assets/idfm/lines_white_small/TRAM_T6.png
    - assets/idfm/lines_white_small/TRAM_T7.png
    - assets/idfm/lines_white_small/TRAM_T8.png
    - assets/idfm/lines_white_small/TRAM_T9.png
    - assets/idfm/lines_white_small/TRAM_T10.png
    - assets/idfm/lines_white_small/TRAM_T11.png
    - assets/idfm/lines_white_small/TRAM_T12.png
    - assets/idfm/lines_white_small/TRAM_T13.png

    - assets/idfm/val/lines/CDGVAL.png
    - assets/idfm/val/lines/ORLYVAL.png
    - assets/idfm/val/lines_small/CDGVAL.png
    - assets/idfm/val/lines_small/ORLYVAL.png

    - assets/idfm/noctilien/NOCT_133.png
    - assets/idfm/noctilien/NOCT_42.png
    - assets/idfm/noctilien/NOCT_52.png
    - assets/idfm/noctilien/NOCT_21.png
    - assets/idfm/noctilien/NOCT_32.png
    - assets/idfm/noctilien/NOCT_43.png
    - assets/idfm/noctilien/NOCT_71.png
    - assets/idfm/noctilien/NOCT_14.png
    - assets/idfm/noctilien/NOCT_66.png
    - assets/idfm/noctilien/NOCT_132.png
    - assets/idfm/noctilien/NOCT_141.png
    - assets/idfm/noctilien/NOCT_145.png
    - assets/idfm/noctilien/NOCT_01.png
    - assets/idfm/noctilien/NOCT_02.png
    - assets/idfm/noctilien/NOCT_131.png
    - assets/idfm/noctilien/NOCT_23.png
    - assets/idfm/noctilien/NOCT_34.png
    - assets/idfm/noctilien/NOCT_31.png
    - assets/idfm/noctilien/NOCT_45.png
    - assets/idfm/noctilien/NOCT_53.png
    - assets/idfm/noctilien/NOCT_16.png
    - assets/idfm/noctilien/NOCT_122.png
    - assets/idfm/noctilien/NOCT_140.png
    - assets/idfm/noctilien/NOCT_24.png
    - assets/idfm/noctilien/NOCT_44.png
    - assets/idfm/noctilien/NOCT_62.png
    - assets/idfm/noctilien/NOCT_22.png
    - assets/idfm/noctilien/NOCT_35.png
    - assets/idfm/noctilien/NOCT_15.png
    - assets/idfm/noctilien/NOCT_153.png
    - assets/idfm/noctilien/NOCT_150.png
    - assets/idfm/noctilien/NOCT_152.png
    - assets/idfm/noctilien/NOCT_135.png
    - assets/idfm/noctilien/NOCT_143.png
    - assets/idfm/noctilien/NOCT_33.png
    - assets/idfm/noctilien/NOCT_61.png
    - assets/idfm/noctilien/NOCT_11.png
    - assets/idfm/noctilien/NOCT_151.png
    - assets/idfm/noctilien/NOCT_134.png
    - assets/idfm/noctilien/NOCT_144.png
    - assets/idfm/noctilien/NOCT_130.png
    - assets/idfm/noctilien/NOCT_51.png
    - assets/idfm/noctilien/NOCT_63.png
    - assets/idfm/noctilien/NOCT_41.png
    - assets/idfm/noctilien/NOCT_13.png
    - assets/idfm/noctilien/NOCT_12.png
    - assets/idfm/noctilien/NOCT_142.png
    - assets/idfm/noctilien/NOCT_154.png

    - assets/sncf/TER_dark.png
    - assets/sncf/TER_white.png
    
    - assets/idfm/TRAIN_white.png
    - assets/idfm/TRAM_dark.png
    - assets/idfm/TRAM_white.png
    - assets/idfm/BUS_dark.png
    - assets/idfm/BUS_white.png
    - assets/idfm/CABLE_dark.png
    - assets/idfm/CABLE_white.png
    - assets/idfm/METRO_dark.png
    - assets/idfm/METRO_white.png
    - assets/idfm/NAVETTE_FLUVIALE_dark.png
    - assets/idfm/NAVETTE_FLUVIALE_white.png
    - assets/idfm/NOCTILIEN_dark.png
    - assets/idfm/NOCTILIEN_white.png
    - assets/idfm/RER_dark.png
    - assets/idfm/RER_white.png
    - assets/idfm/TRAIN_dark.png

    - assets/modal/work_white_small.png
    - assets/modal/alert.png
    - assets/modal/alert_small.png
    - assets/modal/alert_white.png
    - assets/modal/alert_white_small.png
    - assets/modal/error.png
    - assets/modal/error_small.png
    - assets/modal/error_white.png
    - assets/modal/error_white_small.png
    - assets/modal/futur_work.png
    - assets/modal/futur_work_small.png
    - assets/modal/information.png
    - assets/modal/information_small.png
    - assets/modal/information_white.png
    - assets/modal/information_white_small.png
    - assets/modal/interogation.png
    - assets/modal/interogation_grey.png
    - assets/modal/interogation_grey_small.png
    - assets/modal/interogation_small.png
    - assets/modal/interogation_white.png
    - assets/modal/interogation_white_small.png
    - assets/modal/valid.png
    - assets/modal/valid_small.png
    - assets/modal/valid_white.png
    - assets/modal/valid_white_small.png
    - assets/modal/warning.png
    - assets/modal/warning_small.png
    - assets/modal/warning_white.png
    - assets/modal/work.png
    - assets/modal/work_small.png
    - assets/modal/work_white.png
    - assets/null.png
    - assets/walking.png
    - assets/walking_grey.png
    - assets/Here.png
    - assets/Here_small.png
    - assets/location-indicator.png
    - assets/locate.png

    
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
